# Generated by Django 2.2.4 on 2019-08-22 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edotor',
            new_name='Editor',
        ),
    ]
