# Generated by Django 2.2.4 on 2019-08-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tags',
            new_name='tag',
        ),
    ]
