# Generated by Django 2.2.4 on 2019-08-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_editor_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='tag',
        ),
    ]
